return {
    "xiyaowong/transparent.nvim",
    opts = {
        -- groups = {
        --     "Normal",
        --     "NormalNC",
        --     "Comment",
        --     "Constant",
        --     "Special",
        --     "Identifier",
        --     "Statement",
        --     "PreProc",
        --     "Type",
        --     "Underlined",
        --     "Todo",
        --     "String",
        --     "Function",
        --     "Conditional",
        --     "Repeat",
        --     "Operator",
        --     "Structure",
        --     "LineNr",
        --     "NonText",
        --     "SingColumn",
        --     "CursorLine",
        --     "CursorLineNr",
        --     "StatusLine",
        --     "StatusLineNC",
        --     "EndOfBuffer",
        -- },
        extra_groups = {
            "NormalFloat",
            "NvimTreeNormal",
        },
    },
}
